/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TetelekImport } from './routes/tetelek'
import { Route as TetelcreateImport } from './routes/tetelcreate'
import { Route as PmchqImport } from './routes/pmchq'
import { Route as MchoiceqImport } from './routes/mchoiceq'
import { Route as FlashcardsImport } from './routes/flashcards'
import { Route as IndexImport } from './routes/index'
import { Route as TetelekIdImport } from './routes/tetelek/$id'
import { Route as TetelekIdEditImport } from './routes/tetelek/$id/edit'

// Create/Update Routes

const TetelekRoute = TetelekImport.update({
  id: '/tetelek',
  path: '/tetelek',
  getParentRoute: () => rootRoute,
} as any)

const TetelcreateRoute = TetelcreateImport.update({
  id: '/tetelcreate',
  path: '/tetelcreate',
  getParentRoute: () => rootRoute,
} as any)

const PmchqRoute = PmchqImport.update({
  id: '/pmchq',
  path: '/pmchq',
  getParentRoute: () => rootRoute,
} as any)

const MchoiceqRoute = MchoiceqImport.update({
  id: '/mchoiceq',
  path: '/mchoiceq',
  getParentRoute: () => rootRoute,
} as any)

const FlashcardsRoute = FlashcardsImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TetelekIdRoute = TetelekIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TetelekRoute,
} as any)

const TetelekIdEditRoute = TetelekIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TetelekIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsImport
      parentRoute: typeof rootRoute
    }
    '/mchoiceq': {
      id: '/mchoiceq'
      path: '/mchoiceq'
      fullPath: '/mchoiceq'
      preLoaderRoute: typeof MchoiceqImport
      parentRoute: typeof rootRoute
    }
    '/pmchq': {
      id: '/pmchq'
      path: '/pmchq'
      fullPath: '/pmchq'
      preLoaderRoute: typeof PmchqImport
      parentRoute: typeof rootRoute
    }
    '/tetelcreate': {
      id: '/tetelcreate'
      path: '/tetelcreate'
      fullPath: '/tetelcreate'
      preLoaderRoute: typeof TetelcreateImport
      parentRoute: typeof rootRoute
    }
    '/tetelek': {
      id: '/tetelek'
      path: '/tetelek'
      fullPath: '/tetelek'
      preLoaderRoute: typeof TetelekImport
      parentRoute: typeof rootRoute
    }
    '/tetelek/$id': {
      id: '/tetelek/$id'
      path: '/$id'
      fullPath: '/tetelek/$id'
      preLoaderRoute: typeof TetelekIdImport
      parentRoute: typeof TetelekImport
    }
    '/tetelek/$id/edit': {
      id: '/tetelek/$id/edit'
      path: '/edit'
      fullPath: '/tetelek/$id/edit'
      preLoaderRoute: typeof TetelekIdEditImport
      parentRoute: typeof TetelekIdImport
    }
  }
}

// Create and export the route tree

interface TetelekIdRouteChildren {
  TetelekIdEditRoute: typeof TetelekIdEditRoute
}

const TetelekIdRouteChildren: TetelekIdRouteChildren = {
  TetelekIdEditRoute: TetelekIdEditRoute,
}

const TetelekIdRouteWithChildren = TetelekIdRoute._addFileChildren(
  TetelekIdRouteChildren,
)

interface TetelekRouteChildren {
  TetelekIdRoute: typeof TetelekIdRouteWithChildren
}

const TetelekRouteChildren: TetelekRouteChildren = {
  TetelekIdRoute: TetelekIdRouteWithChildren,
}

const TetelekRouteWithChildren =
  TetelekRoute._addFileChildren(TetelekRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/mchoiceq': typeof MchoiceqRoute
  '/pmchq': typeof PmchqRoute
  '/tetelcreate': typeof TetelcreateRoute
  '/tetelek': typeof TetelekRouteWithChildren
  '/tetelek/$id': typeof TetelekIdRouteWithChildren
  '/tetelek/$id/edit': typeof TetelekIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/mchoiceq': typeof MchoiceqRoute
  '/pmchq': typeof PmchqRoute
  '/tetelcreate': typeof TetelcreateRoute
  '/tetelek': typeof TetelekRouteWithChildren
  '/tetelek/$id': typeof TetelekIdRouteWithChildren
  '/tetelek/$id/edit': typeof TetelekIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/mchoiceq': typeof MchoiceqRoute
  '/pmchq': typeof PmchqRoute
  '/tetelcreate': typeof TetelcreateRoute
  '/tetelek': typeof TetelekRouteWithChildren
  '/tetelek/$id': typeof TetelekIdRouteWithChildren
  '/tetelek/$id/edit': typeof TetelekIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flashcards'
    | '/mchoiceq'
    | '/pmchq'
    | '/tetelcreate'
    | '/tetelek'
    | '/tetelek/$id'
    | '/tetelek/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flashcards'
    | '/mchoiceq'
    | '/pmchq'
    | '/tetelcreate'
    | '/tetelek'
    | '/tetelek/$id'
    | '/tetelek/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/flashcards'
    | '/mchoiceq'
    | '/pmchq'
    | '/tetelcreate'
    | '/tetelek'
    | '/tetelek/$id'
    | '/tetelek/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashcardsRoute: typeof FlashcardsRoute
  MchoiceqRoute: typeof MchoiceqRoute
  PmchqRoute: typeof PmchqRoute
  TetelcreateRoute: typeof TetelcreateRoute
  TetelekRoute: typeof TetelekRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsRoute: FlashcardsRoute,
  MchoiceqRoute: MchoiceqRoute,
  PmchqRoute: PmchqRoute,
  TetelcreateRoute: TetelcreateRoute,
  TetelekRoute: TetelekRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flashcards",
        "/mchoiceq",
        "/pmchq",
        "/tetelcreate",
        "/tetelek"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/flashcards": {
      "filePath": "flashcards.tsx"
    },
    "/mchoiceq": {
      "filePath": "mchoiceq.tsx"
    },
    "/pmchq": {
      "filePath": "pmchq.tsx"
    },
    "/tetelcreate": {
      "filePath": "tetelcreate.tsx"
    },
    "/tetelek": {
      "filePath": "tetelek.tsx",
      "children": [
        "/tetelek/$id"
      ]
    },
    "/tetelek/$id": {
      "filePath": "tetelek/$id.tsx",
      "parent": "/tetelek",
      "children": [
        "/tetelek/$id/edit"
      ]
    },
    "/tetelek/$id/edit": {
      "filePath": "tetelek/$id/edit.tsx",
      "parent": "/tetelek/$id"
    }
  }
}
ROUTE_MANIFEST_END */
