/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TetelekImport } from './routes/tetelek'
import { Route as IndexImport } from './routes/index'
import { Route as TetelekIdImport } from './routes/tetelek/$id'

// Create/Update Routes

const TetelekRoute = TetelekImport.update({
  id: '/tetelek',
  path: '/tetelek',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TetelekIdRoute = TetelekIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TetelekRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tetelek': {
      id: '/tetelek'
      path: '/tetelek'
      fullPath: '/tetelek'
      preLoaderRoute: typeof TetelekImport
      parentRoute: typeof rootRoute
    }
    '/tetelek/$id': {
      id: '/tetelek/$id'
      path: '/$id'
      fullPath: '/tetelek/$id'
      preLoaderRoute: typeof TetelekIdImport
      parentRoute: typeof TetelekImport
    }
  }
}

// Create and export the route tree

interface TetelekRouteChildren {
  TetelekIdRoute: typeof TetelekIdRoute
}

const TetelekRouteChildren: TetelekRouteChildren = {
  TetelekIdRoute: TetelekIdRoute,
}

const TetelekRouteWithChildren =
  TetelekRoute._addFileChildren(TetelekRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tetelek': typeof TetelekRouteWithChildren
  '/tetelek/$id': typeof TetelekIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tetelek': typeof TetelekRouteWithChildren
  '/tetelek/$id': typeof TetelekIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tetelek': typeof TetelekRouteWithChildren
  '/tetelek/$id': typeof TetelekIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tetelek' | '/tetelek/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tetelek' | '/tetelek/$id'
  id: '__root__' | '/' | '/tetelek' | '/tetelek/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TetelekRoute: typeof TetelekRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TetelekRoute: TetelekRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/tetelek"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/tetelek": {
      "filePath": "tetelek.tsx",
      "children": [
        "/tetelek/$id"
      ]
    },
    "/tetelek/$id": {
      "filePath": "tetelek/$id.tsx",
      "parent": "/tetelek"
    }
  }
}
ROUTE_MANIFEST_END */
